"""add leitner flashcards

Revision ID: 385a1fb4bfc5
Revises: dd124a8d803d
Create Date: 2025-12-25 15:36:42.860838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385a1fb4bfc5'
down_revision: Union[str, None] = 'dd124a8d803d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_flashcards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('box_number', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['dictionary_words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word_flashcard')
    )
    op.create_index(op.f('ix_user_flashcards_id'), 'user_flashcards', ['id'], unique=False)
    op.create_index(op.f('ix_user_flashcards_user_id'), 'user_flashcards', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_flashcards_word_id'), 'user_flashcards', ['word_id'], unique=False)
    op.add_column('dictionary_words', sa.Column('persian_meaning', sa.Text(), nullable=True))
    op.add_column('dictionary_words', sa.Column('chinese_meaning', sa.Text(), nullable=True))
    op.add_column('dictionary_words', sa.Column('composition', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dictionary_words', 'composition')
    op.drop_column('dictionary_words', 'chinese_meaning')
    op.drop_column('dictionary_words', 'persian_meaning')
    op.drop_index(op.f('ix_user_flashcards_word_id'), table_name='user_flashcards')
    op.drop_index(op.f('ix_user_flashcards_user_id'), table_name='user_flashcards')
    op.drop_index(op.f('ix_user_flashcards_id'), table_name='user_flashcards')
    op.drop_table('user_flashcards')
    # ### end Alembic commands ###
