import { getPlannedCourse, type PlannedCatalogCourse } from "@/lib/plannedCourseCatalog";

const assetRoot = "/assets/chinverse/course-profiles";

const baijiaLessons = [
    { title: "引言", subtitle: "" },
    { title: "第1课", subtitle: "1.1 汉字的性质" },
    { title: "第1课", subtitle: "1.2 西方世界对汉字的认识" },
    { title: "第1课", subtitle: "1.3 树立正确的汉字观" },
    { title: "第2课", subtitle: "2.1 自源文字和借源文字" },
    { title: "第2课", subtitle: "2.2 汉字的起源" },
    { title: "第2课", subtitle: "2.3 中药材里走出的国宝——甲骨文" },
    { title: "第2课", subtitle: "2.4 汉字形体的演变" },
    { title: "第2课", subtitle: "2.5 现代汉字的字体" },
    { title: "第3课", subtitle: "3.1 汉字需要瘦身" },
    { title: "第3课", subtitle: "3.2 新中国的简化字运动" },
    { title: "第3课", subtitle: "3.3 繁体字简化字大比拼" },
    { title: "第3课", subtitle: "3.4 整理异体字" },
    { title: "第3课", subtitle: "3.5 使用规范汉字，纯洁社会用字" },
    { title: "第4课", subtitle: "4.1 中国古代的注音方法" },
    { title: "第4课", subtitle: "4.2 西方传教士的汉语拼音" },
    { title: "第4课", subtitle: "4.3 中国人的拼音化探索" },
    { title: "第5课", subtitle: "5.1 “六书”的来源" },
    { title: "第5课", subtitle: "5.2 《说文解字》介绍" },
    { title: "第5课", subtitle: "5.3 “六书”之象形" },
    { title: "第5课", subtitle: "5.4 “六书”之指事" },
    { title: "第5课", subtitle: "5.5 “六书”之会意" },
    { title: "第5课", subtitle: "5.6 “六书”之形声" },
    { title: "第5课", subtitle: "5.7 汉字的文化阐释" },
    { title: "第5课", subtitle: "5.8 “爱上汉字”之《三十六个字》" },
    { title: "第6课", subtitle: "6.1 笔画" },
    { title: "第6课", subtitle: "6.2 部件" },
    { title: "第6课", subtitle: "6.3 整字" },
    { title: "第7课", subtitle: "7.1 形声字的声旁" },
    { title: "第7课", subtitle: "7.2 形声字的形旁" },
    { title: "第7课", subtitle: "7.3 形声字的结构规律" },
    { title: "第7课", subtitle: "7.4 两用偏旁的再认识" },
    { title: "第8课", subtitle: "8.1 古代识字教材" },
    { title: "第8课", subtitle: "8.2 《文字蒙求》及王筠的识字教育理念" },
];

/** Reference-based course plan; published lessons still come from the public API. */
export const CHARACTER_CATALOG: PlannedCatalogCourse[] = [
    {
        slug: "yoyo-chinese-character",
        title: "Yoyo Chinese (Character)",
        tagline: "یادگیری زبان چینی | از اساس",
        coverPath: `${assetRoot}/Yoyo Chinese.png`,
        lessonCount: 20,
        description: [
            "یه دوره‌ی منظم و خوش‌ساخت برای یاد گرفتن کاراکترهای چینیه، مخصوص کسایی که می‌خوان از حالت حفظ کورکورانه خارج بشن و واقعاً ساختار نوشتاری چینی رو بفهمن.",
            "تو این دوره، یانگ‌یانگ کاراکترها رو به اجزای کوچیک‌تر می‌شکنه و توضیح میده هر بخش چه معنایی داره یا چرا اونجا قرار گرفته. به‌جای اینکه با یه شکل پیچیده روبه‌رو بشی، کم‌کم یاد می‌گیری کاراکترها از «قطعه‌های معنادار» ساخته شدن. همین باعث میشه حفظ کردنشون منطقی‌تر و موندگارتر بشه.",
            "یکی از نقاط قوت این دوره اینه که ترتیب آموزش کاراکترها بر اساس کاربرد و فراکانسه؛ یعنی اول سراغ اونایی می‌ری که واقعاً تو مکالمه و متن‌ها به کارت میان. علاوه بر این، ترتیب صحیح خط‌ها (stroke order) هم دقیق آموزش داده میشه تا از همون اول درست بنویسی.",
            "لحن آموزش مثل بقیه دوره‌های یویو چاینیز صمیمی و قابل فهمه؛ حس کلاس خشک نداره و بیشتر شبیه اینه که یه معلم باحوصله کنارته و قدم‌به‌قدم جلو می‌ره.",
        ],
        audience: [
            "اگه مبتدی هستی و می‌خوای پایه‌ی کاراکترت اصولی شکل بگیره",
            "اگه تو حفظ کاراکترها زود فراموش می‌کنی و دنبال روش منطقی‌تری",
            "اگه می‌خوای بتونی متن‌های ساده رو بخونی و از دیدن کاراکترها نترسی",
        ],
        knownLessonSubtitles: {
            1: "How to Learn Chinese Characters",
            2: "How Many Chinese Characters Do I Need To Learn?",
            3: "The Story Behind Chinese Characters",
            4: "How to Type Chinese Characters Using a Keyboard",
            5: "Should I Learn Simplified or Traditional Chinese Characters?",
            6: "Learn Your First Chinese Character in 5 Minutes– Part 1",
            7: "Learn Chinese Characters in 5 Minutes – Part 2",
            8: "Learn Chinese Characters in 5 Minutes – Part 3",
            9: "Learn Chinese Characters in 5 Minutes – Part 4",
            10: "Learn Chinese Characters in 5 Minutes – Part 5",
            11: "Review for Lessons 6-10",
            12: 'The Story of "Man" – Part 1',
            13: 'The Story of "Man" – Part 2',
            14: 'The Story of "Man" – Part 3',
            15: "Chinese Characters 之 (zhī), 万 (wàn), 历 (lì)",
            16: "Chinese Characters 千 (qiān), 于 (yú), 乎 (hū)",
            17: "Chinese Characters 卡 (kǎ), 片 (piàn), 止 (zhǐ)",
            18: "Chinese Characters 无 (wú), 未 (wèi), and 支 (zhī)",
            19: "Chinese Characters 父 (fù), 交 (jiāo), and 爷 (yé)",
            20: "Review for Lessons 15-19",
        },
    },
    {
        slug: "grace-mandarin-character",
        title: "Grace Mandarin (Character)",
        tagline: "یادگیری زبان چینی | از اساس",
        coverPath: `${assetRoot}/Grace Mandarin.png`,
        lessonCount: 7,
        description: [
            "بخش آموزش کاراکتر گریس ماندارین با رویکرد یک معلم تایوانی ارائه میشه و علاوه بر کاراکترهای ساده‌شده، به نسخه‌ی سنتی (Traditional Chinese) هم توجه داره؛ نکته‌ای که این دوره رو از بسیاری از منابع آنلاین متمایز می‌کنه. تمرکز گریس روی دقت نوشتاری، ترتیب صحیح خط‌ها و درک جزئیات ساختاری کاراکترهاست و آموزش‌ها حالت‌های رسمی‌تر و آکادمیک‌تری دارن. او سعی می‌کنه ارتباط بین تلفظ، معناشناسی و شکل نوشتاری رو روشن کنه و در بعضی بخش‌ها به سیستم Zhuyin هم اشاره می‌کنه که برای کسانی که با منابع تایوانی کار می‌کنن مفیده. این دوره برای زبان‌آموزانی مناسبه که می‌خوان نوشتنشون استاندارد و تمیز باشه یا قصد تحصیل و کار با متون تایوانی و سنتی رو دارن.",
        ],
        audience: [
            "اگه مبتدی هستی و می‌خوای از اول درست نوشتن رو یاد بگیری",
            "اگه تو حفظ کاراکترها مشکل داری و دنبال روش منطقی‌تری هستی",
            "اگه دنبال یاد گرفتن شکل سنتی کاراکترها Traditional Chinese هستی",
        ],
        knownLessonSubtitles: {
            1: "How to learn Chinese Characters",
            2: "Recognize and Write Chinese Characters EASILY! - Part 1",
            3: "Recognize and Write Chinese Characters EASILY! - Part 2",
            4: "Recognize and Write Chinese Characters EASILY! - Part 3",
            5: "Recognize and Write Chinese Characters EASILY! - Part 4",
            6: "Recognize and Write Chinese Characters EASILY! - Part 5",
            7: "The ULTIMATE Guide to Learning Chinese Characters",
        },
    },
    {
        slug: "baijia-talk-hanzi",
        title: "百家Talk (走进汉字)",
        tagline: "یادگیری زبان چینی | از اساس",
        coverPath: `${assetRoot}/百家Talk.jpg`,
        lessonCount: baijiaLessons.length,
        chapterCount: 8,
        description: [
            "ورود به دنیای کاراکترهای چینی (走进汉字) از مجموعه آموزش‌های 百家Talk یه دوره‌ی فرهنگی–تحلیلی درباره‌ی دنیای کاراکترهای چینیه؛ اینجا هدف صرفاً یاد گرفتن نوشتن یا حفظ کردن نیست، بلکه قراره بفهمی هر کاراکتر از کجا اومده، چه مسیری طی کرده و چه داستانی پشتشه. تو این مجموعه با سیر تحول کاراکترها از خط استخوان‌نوشته (甲骨文) تا شکل امروزی آشنا می‌شی و می‌بینی چطور فرهنگ، اسطوره و زندگی روزمره‌ی مردم چین داخل ساختار حروف نفوذ کرده. فضای آموزش بیشتر شبیه یه سخنرانی فرهنگیه تا کلاس زبان؛ بنابراین نگاهت به کاراکترها عمیق‌تر و تاریخی‌تر می‌شه. این دوره بیشتر برای فهم ریشه‌ها و لایه‌های فرهنگی مفیده تا تمرین نوشتن یا آمادگی آزمون.",
        ],
        audience: [
            "سطح پیش‌متوسط به بالا",
            "زبان‌آموزانی که پایه‌ی پین‌یین و کاراکتر رو بلدن",
            "علاقه‌مندان به فرهنگ، تاریخ و ریشه‌شناسی کاراکترهای چینی",
            "افرادی که می‌خوان ارتباط عمیق‌تری با ساختار معنایی کاراکترها برقرار کنن",
        ],
        knownLessonTitles: Object.fromEntries(baijiaLessons.map((lesson, index) => [index + 1, lesson.title])),
        knownLessonSubtitles: Object.fromEntries(baijiaLessons.map((lesson, index) => [index + 1, lesson.subtitle])),
    },
];

export const getCharacterCourse = (slug: string | undefined): PlannedCatalogCourse | undefined =>
    getPlannedCourse(CHARACTER_CATALOG, slug);
