/** Episode topics transcribed in order from the cooking page references. */
export const COOKING_LESSON_TOPICS: Record<string, string[]> = {
    "wanneng-gongjuren-a-wei": [
        "Pickled chili squid | 泡椒鱿鱼",
        "Pickled chili frog legs | 泡椒牛蛙",
        "Pickled chili chicken offal | 泡椒鸡杂",
        "Stir-fried eel with pickled chili peppers | 泡椒火爆黄鳝",
        "Spicy fish with chili peppers | 鱼辣子",
        "Sweet pepper stir-fried pork strips | 甜椒肉丝",
        "Stir-fried shredded pork with green peppers | 青椒肉丝",
        "Stir-fried shredded pork with pickled chili peppers | 泡椒肉丝",
        "Stir-fried shredded pork with yellow chives | 韭黄肉丝",
        "Beijing-style sweet bean sauce shredded pork 京酱肉丝",
        "Chongqing-style “fish-fragrant” shredded pork | 重庆版鱼香肉丝",
        "Shredded pork | 肉丝",
        "Sichuan-style roasted chili century egg | 烧椒皮蛋",
        "Silken tofu with roasted chili peppers | 烧椒嫩豆腐",
        "Steamed fish with roasted chili sauce | 烧椒酱蒸鱼",
        "Roasted chili sauce | 烧椒酱",
        "Eggplant with roasted chili peppers | 烧椒茄子",
        "Beef shank mixed with roasted chili peppers | 烧椒拌牛腱",
        "Steamed pork slices with loofah | 丝瓜蒸肉片",
        "Steamed golden pomfret with scallion oil & black bean sauce | 葱油豉汁蒸金鲳鱼",
        "Lettuce rolls with tofu skin | 豆腐皮生菜卷",
        "Low-cal mixed vegetables salad | 低卡拌时蔬",
        "Millet-steamed beef | 小米蒸牛肉",
        "Water-bath steamed chicken | 隔水蒸鸡",
        "Cold mixed lotus root strips | 凉拌藕条",
        "Mashed potato salad | 土豆泥沙拉",
        "Garlic vermicelli steamed shrimp | 蒜蓉粉丝蒸虾",
        "Steamed pork ribs with double chili peppers | 双椒蒸排骨",
        "Asparagus stir-fried with shrimp | 芦笋炒虾仁",
        "Wholegrain beef steak roll | 粗粮牛排卷",
        "Eggplant | 茄子",
        "Universal soup base | 万能汤底",
        "Water spinach | 空心菜",
        "Oyster sauce lettuce | 蚝油生菜",
        "Cold mung bean jelly salad | 拌凉粉",
        "Steamed oysters with garlic | 蒜蓉蒸生蚝",
        "Macron shrimp | 罗氏虾",
        "Asparagus stir-fried with squid | 芦笋炒鱿鱼",
        "Mustard sea snails & spicy mixed sea snail slices | 芥末花螺和拌海螺片",
        "Fried hairtail fish | 炸带鱼",
        "Pickled cucumber | 黄瓜咸菜",
        "Spicy fermented cabbage (kimchi) | 辣白菜",
        "Pickled vegetables (kimchi) | 泡菜",
        "Braised pork with reishi mushrooms | 鹿茸菇烧肉",
        "Red vinegar pickled radish | 红醋泡萝卜",
        "Crispy pickled cucumber | 脆泡黄瓜",
    ],
    "meishi-zuojia-wang-gang": [
        "Bullfrog with pickled peppers | 泡椒牛蛙",
        "The braised baby fish | 红烧娃娃鱼",
        "Sichuan Braised Chinese Bamboo Rat | 宽油竹鼠",
        "Cold Served Rabbit | 冷吃兔",
        "Braised Bamboo Rat with Bamboo Shoot | 竹笋烧竹鼠",
        "Simmered Chicken with Chili Sauce | 口水鸡",
        "Spicy Stir-Fried Beef Tripe | 辣炒毛肚",
        "Stir-Fried Spicy Silkie Chicken | 小煎乌鸡",
        "Spicy Stir-Fried Swamp Eel | 爆炒土鳝鱼",
        "Zijiang Braised Muscovy Duck | 仔姜烧麻鸭",
        "Ma Ma Fish | 麻麻鱼",
        "Braised Carp in Soy Sauce | 红烧鲤鱼",
        "Braised Duck with Plum Sauce | 冰糖酸梅鸭",
        "Fire Stir-fried Pork Tongue with Scallion | 小葱爆猪舌",
        "Squirrel Fish | 松鼠鱼",
        "Sichuan Chili Beef Tripe | 鲜椒千层肚",
    ],
    "lao-fan-gu": [
        "Lamb Pilaf | 手抓饭",
        "Laofangu-Kung Pao Chicken | 宫保鸡丁",
        "Braised Beef | 红烧牛肉",
        "Cabbage in Boiled Water | 开水白菜",
        "Big Plate Chicken | 大盘鸡",
        "Stir-Fried Shrimp (Zhua-Chao Style) | 抓炒虾仁",
        "Squirrel-Shaped Mandarin Fish | 松鼠桂鱼",
        "Phoenix-Tail Shrimp | 凤尾虾啫粉丝",
        "Braised Eggplant | 烧茄子",
        "Sichuan Pepper Chicken | 椒麻鸡",
        "Braised Prawns in Oil | 油焖大虾",
        "Braised Carp in Soy Sauce | 红烧鲤鱼",
        "THE traditional Mapo Tofu | 麻婆豆腐",
        "Braised Sea Cucumber with Scallions | 葱烧海参",
        "Meat and Chives Dumplings | 韭菜馅饺子",
        "Red Braised Beef Noodles | 红烧牛肉面",
        "Meat Bun | 肉包子",
        "Stir-Fried Tomatoes and Eggs | 西红柿炒蛋",
        "Pan-Seared and Braised Beef Tenderloin | 煎烹牛里脊",
        "Crispy Sweet and Sour Pork | 锅包肉",
        "Oil-Braised Jumbo Prawns | 油焖大虾",
    ],
    "zhongguo-meishi-pindao": [
        "巧克力蛋糕",
        "慕斯蛋糕",
        "冰淇淋",
        "椰蓉小方",
        "马蹄爽",
        "冰红茶",
        "撞奶",
        "老式雪糕",
        "红豆冰棍",
        "冻芒果",
        "冻香蕉",
        "西瓜椰椰冰",
        "钵仔糕",
        "巧克力脆皮雪糕",
        "冰淇淋甜筒",
        "酸奶冰淇淋",
        "奶酪棒",
        "矿泉水瓶做的雪糕",
        "椰蓉牛奶小方",
        "红豆糯米饼",
        "巧克力雪糕",
        "糯米粉",
        "牛奶小布丁雪糕",
        "慕斯蛋糕",
        "红豆西米露",
        "杨枝甘露",
        "芒果慕斯蛋糕",
        "巴巴露亚蛋糕",
        "糯米糍",
        "抹茶味冰山熔岩",
        "菠萝派",
        "奶酪包",
        "奶香玉米",
        "红枣糯米糕",
    ],
};

/** Asset names matched visually to the sixteen Wang Gang reference cards. */
export const WANG_GANG_THUMBNAIL_FILES = [
    "fHhvLoS2n.png",
    "fHh54Qjap.png",
    "fHhwRbxJW.png",
    "fRxdbQ8jS.jpeg",
    "fHh9B2tKH.png",
    "fHiAAPKYR.png",
    "fRxnIPt8O.jpeg",
    "fRxlPoEIo.jpeg",
    "fRxgJHCT2.jpeg",
    "fRxihnWrx.jpeg",
    "fRxjlN9xg.jpeg",
    "fRxodnqMu.jpeg",
    "fHh9xHWNd.png",
    "fHh9tKFIl.png",
    "fHh8Yigg9.png",
    "fHh9nmF3v.png",
];
