/** Exercise topics transcribed from the two reference course pages. */
export const ENERGY_HEALTH_LESSON_TOPICS: Record<string, string[]> = {
    "shi-heng-yi-what-is-qi-gong": [
        "Purpose and Discovery",
        "Ways to Practice and Focus",
        "Different Forms and Benefits",
        "The Direct Transmission",
        "New Year Wake Up",
        "Time To Breath",
        "五松· Wu Song (5 Relaxation / Loosening / Releasing Methods)",
        "Shaolin Chan Gong Rou Quan",
        "20 Minute Daily Morning Routine",
        "罗汉十三式气功 Luohan Postures Soft Fist Form",
        "十三拳· Shi San Quan",
    ],
    "xue-guoxue-wang-baduanjin": [
        "发刊词：古法养生，激活自身免疫力",
        "入门基本功：手型、步型、桩法和呼吸",
        "第一式：两手托天理三焦",
        "第二式：左右开弓似射雕",
        "第三式：调理脾胃须单举",
        "第四式：五劳七伤往后瞧",
        "八段锦阶段动作训练（前四式）",
        "第五式：摇头摆尾去心火",
        "第六式：两手攀足固肾腰",
        "第七式：攒拳怒目增气力",
        "第八式：背后七颠百病消",
        "八段锦完整动作练习",
        "八段锦完整动作练习（呼吸版）",
        "八段锦呼吸方式精讲",
        "八段锦对减肥、增肌、瘦体是否有功效？",
        "八段锦练习有哪些误区？",
        "八段锦手势动作如何用力",
        "八段锦的版本问题",
        "八段锦练习的注意事项",
        "吴蔓老师八段锦直播互动回放",
    ],
};
