/** Episode order and wording from the supplied podcast screens, including repeated titles. */
export const PODCAST_EPISODE_TITLES: Record<string, string[]> = {
    "practical-mandarin": [
        '"Moyu": China\'s Quiet Quitting',
        "破防 | The Moment Your Emotional Wall Collapses",
        "The Rise of New Chinese Style",
        "暧昧期 More Than Friends, Less Than Lovers",
        "你上头了吗 | Are You Obsessed ?",
        "内卷还是躺平？ | Involution or Lying Flat?",
        "中国人过年要穿红内裤？",
        "中国情侣如何过情人节？ | Dating in China.",
        "春节与「拜年」 | Essential Chinese New Year Social Etiquette.",
        "有钱没钱，回家过年 | Rich or Poor, Go Home for New Year",
        "下一站：上岸！ | The Popular Chinese Slang [ ShangAn ]",
        'Paid by Parents? China\'s "Full-time Children"',
        "Da Zi Culture: Temporary Companions in China",
        "Party Hard, Recover Harder?",
        "猫奴 Not Owners, But Slaves? China's Pet Obsession",
        "如何停止精神内耗？ | How to Stop Mental Internal Friction?",
        "吃瓜 Eating Melons is NOT Eating Melons??!",
        "安利 | Anli :Let's Exchange Our Best Learning Secrets!",
        "“意思意思”是什么意思？ | What does “yisi yisi” mean ?",
        "「直男」的多种含义 | Why is Straight Guy an Insult in Chinese?",
        "Milk Tea Culture in China",
        "吃瓜 Eating Melons is NOT Eating Melons??!",
        '特种兵旅游 | The Crazy "Special Forces" Way to Travel',
        "Mike的糟糕情人节 Mike's Terrible Valentine's Day.",
        '凡尔赛文学 | The Art of "Humble Bragging" in China',
        'Why Everyone Calls You "Handsome" in China?',
        "汤圆还是元宵？中国的“南北之争” | The Magic of the Lantern Festival.",
        "Are U an I or an E",
        "嗑CP&狗粮 | Shipping Couples & Dog Food",
        "八方来财 The Money View of Chinese Youth",
        "穿秋裤 Why Your Mom Forces You to Wear QiūKù?",
    ],
    "chinese-podcast-zone": [
        "Lost Motivation to Learn Chinese?",
        "Learn Chinese the Right Way",
        "How to Overcome Procrastination and Learn Chinese Effectively!",
        "Why Sleep Matters",
        "How Do Chinese People Actually Celebrate the New Year?",
        "Legends of Nian & Traditions for the Year of the Horse",
        "Don't Give Up Halfway: Bàn Tú Ér Fèi",
        "Big City vs. Countryside: Which Life Suits You Best?",
        "What's Your Favorite Snack? (Food Vocabulary & Listening)",
        "Learn the Most Common Phrases Chinese People Say",
        "How Chinese People Stay Healthy",
        "Why the Winter Solstice Matters in Chinese Culture",
        "What Is Dongzhi?",
        "What Is Dongzhi? Why the Winter Solstice Matters in Chinese Culture",
        "Christmas Is Coming",
        "Talking About the Weather in Chinese Isn’t Small Talk",
        "The Hidden Risks of Sitting Too Long",
        "How to Order Drinks in Chinese",
        "Enjoy Your Weekend and Learn Chinese with Me!",
        "Let’s Talk About Drinks in Chinese!",
        "How to Introduce Yourself in Chinese Naturally and Confidently!",
        "Learn Chinese & Discover Chengdu",
        "Explore Shanghai, China’s Global Metropolis in Simple Mandarin",
        "What Will You Do This Weekend?",
        "Learn Chinese at the Hotel Check-in",
        "Learn Chinese at the Wet Market",
        "别在机场迷路！学会这些中文就够了",
    ],
    "da-peng": [
        "和美国Peter盛华东一起聊一聊他的中文名字。",
        "抢着买单？聊一聊华东（Peter）在中国“抢买单”的经历。",
        "来自芝加哥的Mason想知道大鹏是谁。",
        "俄罗斯人王力伟在中国旅行的故事。",
        "说韩国（1）「人在他乡 (1)–自行车 & 劝酒」",
        "说韩国（2）「美国快餐和中国快餐 & 韩国午餐和中国午餐」",
        "说韩国（3）「你想变得更美吗？不过，什么是美？」",
        "说韩国（4）「中国的公园 & 韩国的年龄」",
        "说韩国（5）「中文太简单啦！ | 华东要唱歌 & “敬语”和“非敬语”」",
        "说韩国（6）「韩国礼节 & 美国人和中国人，谁说话更直接？」",
        "说韩国（7）「礼节背后的问题」",
        "乡村还是城市？都不是！— “隐居”的澳大利亚田园生活",
        "你是怎么学外语的？",
        "我懂中文，请你直接💋我！",
        "我们的家乡，山西太原。",
        "去中国留学安全吗？",
        "美国的小费应该怎么给？",
        "印尼有多少个岛？",
        "节日没“祝福”？祝福的话很难讲吗？",
        "听大家的声音……新年快乐！",
        "来自Meghan、Franz、Julia和凯琳的新年祝福。",
        "来自越南的新年祝福，Chúc mừng năm mới！",
        "地震，你遇到过吗？",
        "新年祝福，最后一期！",
        "属相，生肖 | 有什么用呢？",
        "电话拜年 | 和在中国的老同学聊聊天儿。",
        "19岁的硕士 | 她怎么可以19岁就硕士毕业呢？",
        "互动话题 2. 说说自己最喜欢的电影。",
        "喝热水，喝冷水。",
        "Flugscham，Flight shame",
        "我爱蟑螂",
        "牛仔节",
        "阿赛雷多 | Aceredo",
        "压力是动力还是压力？",
        "幸运内衣",
        "手语",
        "台湾与大陆，不一样的中文 | 史上最长一集！",
        "请叫我“地球人”",
        "《华东 VS 大鹏》，和Windah快问快答",
        "谁最漂亮？和Windah聊审美",
        "教授禁区 | No Professor Zone",
        "我的旅店开业啦！",
        "高考",
        "应该把帐篷搭在停车场里吗？",
        "你想当演员吗？",
        "Facekini 面基尼",
        "奇怪的气候 · 海象死刑 · 安乐死合法化",
        "谷歌在看你！",
        "听Fred教授讲怎么一边做游戏，一边学中文。",
        "中文老师李如莲的故事",
        "火车旅行",
        "黄金马桶",
        "成语、谚语和歇后语都是啥？",
        "快来参加“快问快答”！",
        "快问快答. 1「小莲」",
        "快问快答. 2「凯琳 🇭🇳」",
        "快问快答. 3「许范锦绣，来自越南。」",
        "快问快答 4「欧姗姗，来自美国德州。」",
        "快问快答 5「陈芳草，来自越南北宁。」",
        "快问快答 6「三天不洗澡 VS 七天不刷牙 | Windah，来自🇮🇩。」",
        "快问快答 7「雅丽，来自🇷🇺的乌拉尔山。」",
        "快问快答 8「王雨涵，来自缅甸🇲🇲。」",
        "快问快答 9「陈氏映，来自越南 🇻🇳。」",
        "快问快答 10「潘氏翠娥，来自越南 🇻🇳。」",
        "快问快答 11「丁庆玲，来自越南 🇻🇳。」",
        "快问快答 12「王国清，来自越南 🇻🇳。」",
        "快问快答 13「阮明壮，来自越南 🇻🇳。」",
        "快问快答 14「玛利亚，来自俄罗斯 🇷🇺。」",
        "快问快答 15「起床后你做的第一件事儿是啥？ | 阮氏玄，来自越南 🇻🇳。」",
        "快问快答 16「阮氏垂蓉，来自越南 🇻🇳。」",
        "快问快答 17「丽幸，来自越南 🇻🇳。」",
        "快问快答 18「普力，来自塔吉克斯坦🇹🇯。」",
        "快问快答 19「嘉慧，来自越南 🇻🇳。」",
        "快问快答 20「保罗，来自法国 🇫🇷。」",
        "快问快答 21「张凌薇，来自泰国 🇹🇭。」",
        "快问快答 22「清闲，来自越南 🇻🇳。」",
        "快问快答 23「日娜，来自伊朗 🇮🇷。」",
        "快问快答 #24 和英竹快问快答",
        "快问快答 #25 快问快答—兰英",
        "这个字用得最多，最常用的汉字！《汉字达人-1》",
    ],
    "bumingbai": [
        "慕容雪村：武汉传来的声音",
        "裴敏欣：上海清零的政治逻辑",
        "润学与最后一代：来自90后00后的心声",
        "伊险峰/杨樱：上海封城中的文艺复兴",
        "何频：中国女性面临的最大困境",
        "白鱼/朱福：如何做一个合格的女权男？",
        "陈志武：风险如何塑造人类文明史",
        "刘亚伟：为什么这么多中国人支持俄罗斯",
        "闾丘露薇：我在波兰做义工 & 中国战狼外交是如何崛起的",
        "叶千荣：安倍遇刺——两个家庭悲剧背后的统一教会",
        "台湾人怎么看佩洛西访台？",
        "葛兆光：传统中国人认识世界的曲折和挫折",
        "Paul Huang：台湾为武统做好准备了吗？",
        "崔静雯：汉服、和服和马面裙",
        "马杰：元宇宙真的来了吗？",
        "许成钢：中国经济还有希望吗？",
        "金冬雁：新冠清零还会持续多久？",
        "Victor Shih：从中共历史上党争看20大高层走向",
        "江雪/张洁平：中国媒体过去10年发生了什么？",
        "蔡霞：我为什么对中共绝望？",
        "吴国光：极权时代反抗的可能性",
        "吴国光：20大结局与中国未来走向",
        "四通桥后，那些年轻的抗议者",
        "Scott Kennedy：中美关系还有回头的可能吗？",
        "裴敏欣：习近平权力的悖论",
        "孙韵：“习拜会”后中美关系会怎么走？",
        "那些年轻的抗议者：我们为什么要上街",
        "蔡霞：如何看待江泽民的政治遗产？",
        "那些年轻的抗议者：被捕之后",
        "金冬雁：如何应对新冠大爆发",
        "黄严忠：放开之后一个公共卫生专家的建议",
        "[精选]伊险峰/杨樱：上海封城中的文艺复兴",
        "王志安：央视、审查和“大外宣”",
        "萧瀚：中国古代的女改革家",
        "Victor Shih：地方债会拖垮中国经济吗？",
        "许成钢：从ChatGPT看中美人工智能竞争",
        "Tinyfool：ChatGPT会如何改变我们的生活",
        "俄乌战争一周年，台湾学到了什么？",
        "胡不归：我们为什么需要记住疫情三年",
        "长臂审查：中国如何影响在海外的艺术家",
        "《瞬息全宇宙》为何能拿奖拿到手软？",
        "沈栋：红色赌盘——中国权力高层的共谋者",
        "谁是许志永，谁是丁家喜？",
        "Lynette Ong：中国如何利用“外包镇压”控制社会",
        "女权开麦：说脱口秀，做自由人",
        "黄亚生：科举制度如何影响中国的未来",
        "赵越胜：习近平治下中国外交为何大转向",
        "谁是“编程随想”？",
        "慕容雪村：在流亡中写作",
        "王春翰：习近平是如何崛起的",
    ],
};
