/** Love Chinese vocabulary card subtitles in the order shown in the owner's screenshots. */
export const LOVE_CHINESE_VOCABULARY_TOPICS = [
    "60 Common Chinese Words about Maritime Shipping",
    "40 Essential Chinese Sentences about Ocean Transport",
    "Petroleum & Natural Gas Vocabulary",
    "60 Common Chinese Traffic Safety Words",
    "50 Common Construction Site Vocabulary in Chines (Part 1)",
    "Construction Site Vocabulary in Chinese (Part 2)",
    "60 Chinese Preschool Vocabulary Words for Kids",
    "60 Chinese Toy Vocabulary Words for Kids",
    "60 Common Chinese Political Vocabulary Words",
    "60 Essential Legal Terms in Chinese",
    "Detective and Crime Vocabulary Revealed",
    "60 Common Chinese War Vocabulary Words",
    "60 Essential Chinese Gaming & Esports Words",
    "60 Chinese Rude & Slang You Should Know (But Not Use!)",
    "60 Common Chinese History Vocabulary Words",
    "Classroom Objects Vocabulary in Chinese",
    "Workshop Tools",
    "Learn Chinese Insect Names",
    "Opposite words in Chinese with Pictures and Sentences",
    "Fruits in Chinese with Pictures",
    "50 Common administration vocabulary",
    "50 Must Know Black Myth Wukong Game Vocabulary",
    "70 Common Chinese Geography Words",
    "60 Common Chinese Vocabulary Words about Movies",
    "60 Common Chinese Vocabulary Words about Music & Musical Instruments",
    "60 Common Chinese Fitness Vocabulary Words",
    "60 Essential Chinese Words for the Garment Industry",
    "Family & Relationships Vocabulary in Chinese",
    "60 Must-Know Chinese Art & Culture Terms",
    "60 Must-Know Nature & Environment Terms",
    "Makeup Vocabulary for Beginners",
    "60 Must-Know Chinese Food Terms",
    "Essential Chinese & Western Seasoning Vocabulary",
    "50 Must-Know Chinese New Year Terms & Traditions",
    "50 Must-Know Chinese Social Media Terms",
    "50 Must-Know Networking Terms for IT Beginners",
    "Learn Common Auto Repair Vocabulary in Chinese",
    "Master Car Parts Vocabulary in Chinese",
    "Learn Cryptocurrency & Trading Vocabulary in Chinese",
    "Learn Common Traditional Chinese Medicine Terms",
    "50 Common Software Development Terms",
    "Common Diseases Vocabulary in Chinese",
    "Daily Activities Vocabulary in Chinese",
    "Learn 50 Common Emotions and Feelings Vocabulary in Chinese",
    "Learn Essential Restaurant & Food Vocabulary in Chinese",
    "Learn Essential Chinese Shopping & Market Vocabulary",
    "Learn Chinese & International Festival Vocabulary",
    "Essential Chinese Travel Vocabulary",
    "Learn Essential Financial Terms in Chinese",
    "Learn Chinese Colors & Shapes Vocabulary with Pinyin",
    "Learn Chinese Weather and Seasons Vocabulary",
    "Learn Chinese Body Parts Vocabulary",
    "Learn Chinese Vegetables Vocabulary",
    "50 Common Clothes Vocabulary in Chinese",
    "50 Common Medical Equipment Vocabulary in Chinese",
    "Learn 50 Common Sports Vocabulary in Chinese",
    "Learn 50 Essential Bathroom Vocabulary in Chinese",
    "Master School Vocabulary",
    "Learn 50 Common Vehicle Vocabulary in Chinese",
    "Learn Bedroom Items in Chinese",
    "Discover Ocean Creatures in Chinese",
    "Learn Common Professions in Chinese",
    "Learn Wild Animals in Chinese",
    "Learn Common City Places in Chinese",
    "Learn Chinese Verbs (Part 1)",
    "Learn Chinese Verbs (Part 2)",
    "Master Chinese Kitchen Vocabulary",
    "Learn Chinese Farm Animals",
    "Learn Chinese Flower Names",
];
