/** Card subtitles transcribed in the order shown by the owner's vlog screenshots. */
export const ZHANGKAI_VLOG_TOPICS = [
    "No Vocab Memorization, No Grammar Study",
    "Learn Chinese Through My Night Routine",
    "Learn Chinese While Shopping at the Supermarket",
    "Learn Chinese at the Park",
    "Learn Chinese at the Fruit Shop",
    "Learn Chinese While Touring My Home",
    "The Only Fast Way to Learn Chinese Is Right Here",
    "Learn Chinese by Taking the Subway",
    "Learn Chinese by Shopping at the Supermarket",
    "Learn Chinese While Dining at a Restaurant",
    "Learn Chinese While Wandering Around the Mall",
    "40 Chinese Action Verbs Used Every Day",
    "Learn Chinese While Eating Snacks",
    "Learn Chinese While Traveling Part 1",
    "Learn Chinese While Traveling Part 2",
    "20 Daily-Used Chinese Words Related to the Body",
    "Learn Chinese While Cooking",
    "Learn Chinese Through My Morning Routine",
    "Learn Chinese Through My Shopping",
    "30 Common Fruits, a Must-Learn for Chinese Beginners!",
    "Learn Chinese Through Travel",
    "Learn Chinese Through Eating Meals With My Family",
    "Learn Chinese Through Having Breakfast",
    "Learn Chinese Through Christmas Decorations",
    "Learn Chinese Through Buying Groceries at the Supermarket",
    "Learn Chinese Through Doing Housework",
    "Learn Chinese Through Evening Walks",
    "Learn Chinese Through Spending Weekends With Pets",
    "Guaranteed Ways to Learn Chinese Here",
    "Learn Chinese Through Making Lunch",
    "Learn Chinese Through Dining at a Seafood Restaurant",
    "Learn Chinese Through Walking",
    "Learn Chinese Through My Morning Routine",
    "Learn Chinese Through Supermarket Shopping",
    "Learn Chinese Through My Lunch",
    "Learn Chinese Naturally Through My Work",
    "Learn Chinese Through Our Shopping Trip",
    "Learn Chinese Through Introducing My Furniture",
    "Learn Chinese Through My Pre-Trip Preparations",
    "What is the Correct Way to Learning Chinese?",
    "Learn Chinese Through Making My Lunch 2",
    "Learn Chinese Through Grocery Shopping -Episode 1",
    "Learn Chinese Through Grocery Shopping - Episode 2",
    "Learn Chinese Through Grocery Shopping - Episode 3",
    "Learn Chinese Through Cabinet Repair",
    "Learn Chinese While Having Breakfast",
    "Learn Chinese While Touring My Living Room 1",
    "Learn Chinese While Touring My Living Room 2",
    "Learning Chinese During My Trip to Japan",
    "Chinese Related to the Bathroom",
    "Learn Chinese Related to the Bathroom",
    "Learn Chinese Naturally While I Cook",
    "Learn Chinese in the Car",
    "Learn Chinese through walking",
    "Learn Chinese Through Chinese New Year",
];

export const HONGCHA_VLOG_TOPICS = [
    "学中文并不难1 | Is learning Chinese Hard? part 1",
    "汉语拼音 | All the content about Chinese Pinyin",
    "学中文并不难2 | Is learning Chinese Hard? part 2",
    "逛超市 学中文 | learn Chinese in a supermarket",
    "中国大学食堂 | University canteen in China",
    "逛中国商场 | Chinese ShoppingMall",
    "漫步南京路 | Travel in China-Shanghai",
    "乘地铁 游外滩 | China's Subway and learn Chinese",
    "在厨房 学中文 | What's in a Chinese kitchen?",
    "看视频 学中文 | Learn Chinese in bathroom",
    "冰箱里有什么 | What's in the fridge?",
    "在餐厅 学中文 | Learn Chinese in dining room",
    "做家务 学中文 | Do housework",
    "点咖啡 学中文 | Order luckin coffee",
    "超市里 学中文 | What's in Chinese Supermarket?",
    "桌子上有什么 | What's on my desk?",
    "卧室里 学中文 | What's in my bedroom?",
    "书店里 学中文 | Chinese Bookstore in Shanghai",
    "书店里还有什么 | Learn Chinese in a bookstore 2",
    "汽车部件怎么讲 | CAR parts in Chinese",
];

export const FREE_TO_LEARN_VLOG_TOPICS = [
    "房间 & 家具词汇",
    "在家门口看到了奥运圣火",
    "广州机场 24 小时转机攻略",
    "带你去吃Biángbiáng面",
    "如何在中国叫外卖 & 叫网约车？",
    "带你吃海鲜 - 看餐厅机器人",
    "去中国必备 - 从机场到酒店全攻略！",
    "12 个旅行必备中文 | 签证、交通、酒店、租房！",
    "搞懂酒店房型和设施！入住退房全攻略！",
    "最常用的酒店预订表达！",
    "你的饮食健康吗？",
    "你会定期体检吗？",
    "元宵节",
    "带你过中国新年",
];

export const HI_CHINESE_VLOG_TOPICS = [
    "Garbage sorting – have you learned how to do it?",
    "Your Mom Asks You to Drink Hot Water!",
    "I am a single DOG (我是单身狗)",
    "Do you know 豹纹（bào wén）?",
    "My Tiny Life（我的小生活）",
    "Fried Egg Fridge Magnet DIY（煎鸡蛋冰箱贴）",
    "During COVID-19, See the World-Korea",
    "During COVID-19, See the World-Turkey",
    "During COVID-19, See the World- Japan",
    "During COVID-19, See the World- U.S.A",
    "During COVID-19, See the World- Italy",
    "During COVID-19, See the World- Spain",
    "Make Spicy Pot Abroad!",
    "Which clothing store do you want to go to?",
    "A Day of Chinese Teacher - Pusan",
    "What Chinese Snacks Can You Get in Korea?",
    "Red Envelope Plan of a Multicultural Family!",
    "A Chinese Family's Fight Against Coronavirus",
    "Chinese and Korean Kids Teach You how to Fight Against the Coronavirus",
];

export const ZHANGKAI_SHORT_TOPICS = [
    "小猫咪出喜片", "去厕所怎么问？", "水龙头", "睡前仪式1", "睡前仪式2",
    "睡前仪式3", "睡前仪式4", "睡前仪式5", "晴天1", "晴天2",
    "公园1", "公园2", "公园3", "常用动词1", "常用动词2",
    "常用动词3", "常用动词4", "常用动词5", "常用动词6", "常用动词7",
    "常用动词8", "常用动词9",
];
